export const CHALLENGE_GET_REQUEST = "CHALLENGE_GET_REQUEST";
export const CHALLENGE_GET_SUCCESS = "CHALLENGE_GET_SUCCESS";
export const CHALLENGE_GET_FAIL = "CHALLENGE_GET_FAIL";

export const CHALLENGE_ADD_REQUEST = "CHALLENGE_ADD_REQUEST";
export const CHALLENGE_ADD_SUCCESS = "CHALLENGE_ADD_SUCCESS";
export const CHALLENGE_ADD_FAIL = "CHALLENGE_ADD_FAIL";

export const CHALLENGE_DETAILS_REQUEST = "CHALLENGE_DETAILS_REQUEST";
export const CHALLENGE_DETAILS_SUCCESS = "CHALLENGE_DETAILS_SUCCESS";
export const CHALLENGE_DETAILS_FAIL = "CHALLENGE_DETAILS_FAIL";

export const CHALLENGE_UPDATE_REQUEST = "CHALLENGE_UPDATE_REQUEST";
export const CHALLENGE_UPDATE_SUCCESS = "CHALLENGE_UPDATE_SUCCESS";
export const CHALLENGE_UPDATE_FAIL = "CHALLENGE_UPDATE_FAIL";

export const CHALLENGE_DELETE_REQUEST = "CHALLENGE_DELETE_REQUEST";
export const CHALLENGE_DELETE_SUCCESS = "CHALLENGE_DELETE_SUCCESS";
export const CHALLENGE_DELETE_FAIL = "CHALLENGE_DELETE_FAIL";

export const CHALLENGE_PUT_REQUEST = "CHALLENGE_PUT_REQUEST";